remote_theme: poole/hyde
#brianmaierjr/long-haul

title: Loan Defaulter

url: https://github.com/RenaissanceMan06/Loan_Defaulter
baseurl: /
markdown: redcarpet
highlighter: pygments

description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'

paginate: 5


author: Rene Solis
