remote_theme: poole/hyde
#brianmaierjr/long-haul

title: Loan Defaulter

url: https://github.com/RenaissanceMan06/Loan_Defaulter
baseurl: /
markdown: redcarpet
highlighter: pygments

paginate: 5

navigation:
  - title: Home
    url: /index.html



author: Rene Solis
