remote_theme: emilbaehr/automatic-app-landing-page 
#brianmaierjr/long-haul

title: Loan Defaulter

url: https://github.com/RenaissanceMan06/Loan_Defaulter
baseurl: "/Loan_Defaulter"
markdown: kramdown
highlighter: rouge

paginate: 1

navigation:
  - title: Home
    url: /index.html



social:
  github: RenaissanceMan06 

author: Rene Solis
