theme: jekyll-theme-slate
#remote_theme: daattali/beautiful-jekyll

author: 'Rene Solis'

title: Loan Defaulter

url: https://github.com/RenaissanceMan06/Loan_Defaulter

markdown: redcarpet
highlighter: pygments

paginate: 5




