remote_theme: brianmaierjr/long-haul

url: https://github.com/RenaissanceMan06/Loan_Defaulter
baseurl: "/Loan_Defaulter"
markdown: kramdown
highlighter: rouge


navigation:
  - title: Home
    url: https://github.com/RenaissanceMan06/Loan_Defaulter


social:
  github: renesolis

author: Rene Solis
