remote_theme: daattali/beautiful-jekyll

title: Loan Defaulter

url: https://github.com/RenaissanceMan06/Loan_Defaulter
baseurl: /
markdown: redcarpet
highlighter: pygments

paginate: 5


author: 'Rene Solis'


