remote_theme: brianmaierjr/long-haul

title: Loan Defaulter

url: https://github.com/RenaissanceMan06/Loan_Defaulter
baseurl: "/Loan_Defaulter"
markdown: kramdown
highlighter: rouge

paginate: 1

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about


social:
  github: renesolis

author: Rene Solis
