remote_theme: mmistakes/minimal-mistakes
#remote_theme: daattali/beautiful-jekyll

minimal_mistakes_skin    : "default"

title: Loan Defaulter

url: https://github.com/RenaissanceMan06/Loan_Defaulter

markdown: redcarpet
highlighter: pygments

paginate: 5


author: 'Rene Solis'



theme: jekyll-theme-slate